# Tutorial-2 Jan 20 Get started with PyTorch
* Basic contents of PyTorch
    * Data Manipulation
    * Linear Algebra
    * Automatic Differentiation
* Linear regression
    * Implement from scratch
    * Consise Implement

# Data Manipulation

In order to get anything done, we need some way to store and manipulate data.
Generally, there are two important things we need to do with data: 
* acquire them; 
* process them once they are inside the computer. 

To start, we introduce the
$n$-dimensional array, which is also called the *tensor*.

If you have worked with NumPy, the most widely-used
scientific computing package in Python,
then you will find this section familiar.

The *tensor class* is similar to NumPy's `ndarray` with
a few killer features.
1. GPU is well-supported to accelerate the computation. NumPy only supports CPU computation.
2. the tensor class supports automatic differentiation.

These properties make the tensor class suitable for deep learning.

## Getting Started

To start, we import `torch`.

In [4]:
import torch

By invoking `arange(n)`, we can create a vector of evenly spaced values,
starting at 0 (included) 
and ending at `n` (not included).

By default, the interval size is $1$.

In [5]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

**We can access a tensor's *shape*** by inspecting its `shape` property.


In [6]:
x.shape

torch.Size([12])

**To change the shape of a tensor without altering
either the number of elements or their values**,
we can invoke the `reshape` function.

In [7]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

Reshaping by manually specifying every dimension is unnecessary.

We invoke this capability by placing `-1` for the dimension
that we would like tensors to automatically infer.
In our case, instead of calling `x.reshape(3, 4)`,
we could have equivalently called `x.reshape(-1, 4)` or `x.reshape(3, -1)`.

In [8]:
X2 = x.reshape(3, -1)
X2

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

Create tensors with each element set to 0

In [9]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Similarly, we can create tensors with each element set to 1 as follows:


In [10]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

**Randomly sample the values
for each element in a tensor**

Each of its elements is randomly sampled
from a standard Gaussian (normal) distribution
with a mean of 0 and a standard deviation of 1.

In [11]:
torch.randn(3, 4)

tensor([[-1.0726,  0.8836,  2.0123,  0.0063],
        [ 1.3696, -0.6672,  0.6206,  0.0129],
        [-0.9573, -2.3335,  0.0544, -2.0171]])

We can also **specify the exact values for each element** based on a Python list

In [12]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## Operations

The common standard arithmetic operators
(`+`, `-`, `*`, `/`, and `**`)
have all been *lifted* to elementwise operations
for any identically-shaped tensors of arbitrary shape.
We can call elementwise operations on any two tensors of the same shape.

### Operations


In [13]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # The ** operator is exponentiation

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

We can also ***concatenate* multiple tensors together,**
stacking them end-to-end to form a larger tensor.
We can stack them both at axis 0 and 1.

In [14]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

Sometimes, we want to **construct a binary tensor via *logical statements*.**

In [15]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [7]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

**Summing all the elements in the tensor** yields a tensor with only one element.


In [16]:
X.sum()

tensor(66.)

Count the number of elements of X

In [17]:
X.numel()

12

## Broadcasting Mechanism

Before, we saw how to perform elementwise operations
on two tensors of the same shape. 

Under certain conditions,
even when shapes differ, we can still **perform elementwise operations
by invoking the *broadcasting mechanism*.**

1. expand one or both arrays so that the two tensors have the same shape.
2. carry out the elementwise operations


In [15]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

`a` and `b` are $3\times1$ and $1\times2$ matrices respectively.

We will *broadcast* the entries of both matrices into a larger $3\times2$ matrix as follows:

In [16]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

The result will be the same as:

In [9]:
a2 = torch.tensor([[0, 0], [1, 1], [2, 2]])
b2 = torch.tensor([[0, 1], [0, 1], [0, 1]])
a2, b2

(tensor([[0, 0],
         [1, 1],
         [2, 2]]),
 tensor([[0, 1],
         [0, 1],
         [0, 1]]))

In [10]:
a2 + b2

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## Indexing and Slicing

Just as in any other Python array, elements in a tensor can be accessed by index.

Notice that **`[-1]` selects the last element and `[1:3]`
selects the second and the third elements**


In [11]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

**We can also write elements of a matrix by specifying indices.**


In [18]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

If we want **to assign multiple elements the same value,
we simply index all of them and then assign them the value.**

`:` takes all the elements along an axis (column or row).

In [19]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## Conversion to Other Python Objects


**Converting to a NumPy tensor (`ndarray`)**], or vice versa, is easy.

In [18]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

To **convert a size-1 tensor to a Python scalar**,
we can invoke the `item` function or Python's built-in functions.


In [24]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)